// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHJL1Fim3nafQYlCVN_d0A9qN1WKdx7NE',
    appId: '1:380741780358:web:38b676a07fd12b7083a207',
    messagingSenderId: '380741780358',
    projectId: 'adpotter-1d5c7',
    authDomain: 'adpotter-1d5c7.firebaseapp.com',
    storageBucket: 'adpotter-1d5c7.appspot.com',
    measurementId: 'G-SYJP3CM2LX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAu3R3nuJW5qoYiPXq3S08vPcx7qc6buRY',
    appId: '1:380741780358:android:8e30ae23e1181fc483a207',
    messagingSenderId: '380741780358',
    projectId: 'adpotter-1d5c7',
    storageBucket: 'adpotter-1d5c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAo3Y6b6wYPdqOHn4J4vCZ8zh_-fidR704',
    appId: '1:380741780358:ios:daa047d192a0fdf183a207',
    messagingSenderId: '380741780358',
    projectId: 'adpotter-1d5c7',
    storageBucket: 'adpotter-1d5c7.appspot.com',
    iosClientId: '380741780358-d3726cek25dkls7gf36atpm8bl5nf2ne.apps.googleusercontent.com',
    iosBundleId: 'com.example.adspotter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAo3Y6b6wYPdqOHn4J4vCZ8zh_-fidR704',
    appId: '1:380741780358:ios:daa047d192a0fdf183a207',
    messagingSenderId: '380741780358',
    projectId: 'adpotter-1d5c7',
    storageBucket: 'adpotter-1d5c7.appspot.com',
    iosClientId: '380741780358-d3726cek25dkls7gf36atpm8bl5nf2ne.apps.googleusercontent.com',
    iosBundleId: 'com.example.adspotter',
  );
}
